pre-commit:
  jobs:
    - name: ruff
      glob: "*.py"
      group:
        piped: true
        jobs:
          - name: format
            run: .venv/bin/ruff format --force-exclude --exit-non-zero-on-format {staged_files}
          - name: check
            run: .venv/bin/ruff check --force-exclude --fix --exit-non-zero-on-fix {staged_files}
