[project]
name = "celery_redis_prometheus"
description = "Exports task execution metrics in Prometheus format"
version = "2.0.0.dev0"

dependencies = [
    "celery >= 5.0.0.dev0",
    "click",
    "prometheus_client >= 0.14.0",
]

authors = [{name="DIE ZEIT", email="engineering@zeit.de"}]
license = {text="BSD-3-Clause"}
urls = {repository="https://github.com/ZeitOnline/celery_redis_prometheus"}
requires-python = ">=3.7"

dynamic = ["readme"]

[project.entry-points."celery.commands"]
prometheus = "celery_redis_prometheus.exporter:main"

[dependency-groups]
dev = ["pytest"]
lint = ["lefthook", "ruff"]
release = ["towncrier"]


[build-system]
requires = ["hatchling", "hatch-fancy-pypi-readme"]
build-backend = "hatchling.build"

[tool.hatch.build]
exclude = ["/bin", "/changelog"]

[tool.hatch.metadata.hooks.fancy-pypi-readme]
content-type = "text/markdown"
fragments = [{path="README.md"}, {text="\n\n"}, {path="CHANGES.md"}]


[tool.pytest.ini_options]
addopts = "--tb=native"


[tool.towncrier]
directory = "changelog/"
filename = "CHANGES.md"
start_string = "<!-- towncrier release notes start -->\n"
title_format = "## {version} ({project_date})"
underlines = ["", ""]

[[tool.towncrier.type]]
directory = "change"
name = ""
showcontent = true


[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "I"]
fixable = ["ALL"]

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint.isort]
from-first = true
lines-after-imports = 2
